#!/bin/bash

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


if [ "$1" == "--wstunnel" ]; then
  shift
  WSTUNNEL_SERVER="$1"
  shift
fi

if [ -z "$WSTUNNEL_SERVER" ]; then
  echo "You must provide a wstunnel proxy server either with --wstunnel <server> or set WSTUNNEL_SERVER in the environment" >&2
 exit 1
fi

ssh -o ProxyCommand="$SCRIPT_DIR/wstunnel client --keepalive 2m '$WSTUNNEL_SERVER' stdio:%h:%p 2>/dev/null" "$@"
